### ISSUE TITLE
Sorting rows problems if there are more then 10 schedulers

### ISSUE THREAD

**Issue by janandersnolemo** [arthurdent75/SimpleScheduler#61] opened 2022-04-02 13:43 UTC
When trying to sort the different tasks, the sorting will not remain. When refreshing the page, the tasks will be unsorted (or sorted in a completely different manner).
Can't find any sorting settings in the FAQ.

Is this an issue or is the issue at my side?
BR
/J-A N

**Comment by arthurdent75** [comment] 2022-04-02 14:05
I think this is something related to you. 
What browser are you using? Have you tried a different browser?
Can you check in the console of your browser (developer option or something similar) if there is any javascript error?

**Comment by janandersnolemo** [comment] 2022-04-02 14:18
SOLVED!
Deleted all rows and started all over again, now it works.
Some work to do all these delete and add again but this scheduler is worth spending some care.
Before I tried chrome and edge, all the same sorting issues.
So your'e probably correct, the fault is mine... (don't know why the error occurred)
Thanks for extremely fast response :-)

**Comment by arthurdent75** [comment] 2022-04-02 16:12
Glad to hear you solved it, but sorry about all the work.
Hope you never get this issue again, but just in case keep these in mind:

first of all, install the SAMBA addon, so you have access to files

every scheduler is a JSON file in the _\\\\<homeassistant_ip_address>\share\simplescheduler_ folder
you can copy the files elsewhere, delete them and copy them back there to restore them.

In the same folder, you will find the file _sort.dat_ that keeps the sorting information.
You can delete it. It will be recreated as soon as you will sort the list again.

**Comment by janandersnolemo** [comment] 2022-04-02 16:38
Thanks, 
Dont mention it, its a small effort compare the work you have done creating this scheduler.
Im just happy to have this scheduler :-)
The issue can be closed.

**Comment by janandersnolemo** [comment] 2022-04-03 16:17
It happend again.
I write some comments if you want to look into the matter...

Suddenly when I was adding timers and rearranging them the sorting was messed up again.
I deleted the last timer without any improvements, sorting was still not working, 
after sorting timers the sorting is messed up after refresh.

Some fault tracing...
- Restarted HA (Core, Supervisor, Host) and rebuild the Scheduler - No improvement
- Removed sort.dat - No improvement
- Manually rearranged the timers in sort.dat - No improvements
- When rearranging the timers, the sort.dat do changes in correct manner (the timers identity is at correct sorting) but when refreshing Scheduler the sorting will not reflect the sorting in sort.dat 
- With the "correct" sorting in sort.dat, if moving just one timer, the sort.dat WILL uppdate, but with the "wrong" sorting as in the UI.
- After rearrange the timers, the sort.dat is in correct order, but when refreshing the sorting is messed up again.

Conclusion:
- Regardless of content in sort.dat, the sorting wont reflect that sorting.

Possible reason:
- It seems that Scheduler dont read as supposed from sort.dat, maybe it uses some cache somewhere.

For what all this is worth...
IF you have some ideas please give me a hint how to proceed (when time is..)

I haven't yet uninstalled/reinstalled (Im a bit nervous that the already installed timers will disappear)
BR
/Jan-Anders

**Comment by arthurdent75** [comment] 2022-04-03 17:27
Sorry to hear that.
Sorting is achieved with javascript. The page loads the items in the order they were created and as soon as the load finishes a javascript function sorts them with the info from the file sort.dat
So something is definitely going wrong between your browser and javascript.

To help me debug this (which never occurs to me so it is difficult for me to understand) you may:
- tell me which browser you are using and try to use another browser
- try to use another computer (it may seem stupid but it helps me to figure out if the issue is related to your browser or to your timers)
- if you use the mobile app (android or ios) check if you have the same issue
- open the developer tools of your browser and look if there are errors in the console 

Don't worry, we will figure it out!

**Comment by janandersnolemo** [comment] 2022-04-03 19:51
Well, its a small annoying glitch, the basic function is great. But it would be nice to get it sorted out :-)
 
Home Assistant 2022.3.8
Runs on a Virtual machine (WMWare), supervised
I'm using https
 
Browsers:
Same sorting issues in all of them:
Chrome - Version 100.0.4896.60 (Officiell version) (64 bitar)
Opera  - Version:84.0.4316.42
Edge   - Version 100.0.1185.29 (Officiell version) (64 bitar)

OS:
Windows 10 Home, 21H1, 19043.1586, Windows Feature Experience Pack 120.2212.4170.0

Different computer - Same issue

Also restarted computer - Same issue

Mobile apps, was not able to drag and sort in the app
- iPhone 11
- Android 5.1.1

Errors in console (All levels):
0422c555.js:1 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write

Ill try on another computer tomorrow.

BR
/Jan-Anders

**Comment by arthurdent75** [comment] 2022-04-03 20:08
Thank you for such details.
I can exclude for sure that is something related to the browser or the PC.
The next step is to understand if one of the timers creates the issue.
Please, take a copy of all the JSON files from the \\<homeassistant_ip_address>\share\simplescheduler folder into your computer.
Then start to delete the JSON files one by one from the share. Every time you delete one file, check if the issue is solved.
Try to understand if the issue is somehow related to one of the timers.
After that, you can copy back the files in the share to restore all the timers.

Thank you for all your help.

**Comment by janandersnolemo** [comment] 2022-04-04 07:05
Thanks for sharing the information of how you store the individual schedules, that's quite useful.
Just checked yet another computer, same sorting issues (just to check)

Removed the schedules one by one and found a possible thread to look into.
When exceeding 10 schedules, the sorting stop working.

Removed schedules and when sorting worked when it was 10 and less.
None of the schedules were faulty (in the sorting aspect), I could use every one of them and the sorting would work when the number was 10 and below. When I reached 11 schedules, the sorting started to go nuts. Even tried with 10 of my "old" schedules and added one completely new. When exceeding 10, sorting started to be crazy.

Hope this can be to some help

BR
/Jan-Anders

**Comment by arthurdent75** [comment] 2022-04-04 08:04
Thank you so much. It is more than helpful.
I must confess I never tried to add more than 10 schedulers.
I will try to reproduce the issue.

**Comment by arthurdent75** [comment] 2022-04-04 08:13
Find the bug and fixed!
Thank you for your precious help.
I was about to release a new version in a few days with new features and I will include this fix.
Just a little bit of patience.
Thanks again!

**Comment by janandersnolemo** [comment] 2022-04-04 08:27
Great!
Glad do be to some help to this scheduler since its quire simple and does the work :-)
Don't rush into it, do the fix in a controlled manner. I certainly have the patience.
Again, thanks for this Scheduler :-)

**Comment by arthurdent75** [comment] 2022-04-10 06:33
Fixed with release 0.50!

**Closed by arthurdent75** 2022-04-10 06:33 UTC
