### ISSUE TITLE
Error "Error:Connection failed! (Error: 0x00 0x00)" after updating to 0.60

### ISSUE THREAD

**Issue by maurizioandreotti60** [arthurdent75/SimpleScheduler#68] opened 2022-05-31 12:34 UTC
I just updated to release 0.60 and the Scheduler seems to working fine, but looking at the log I see a lot of error messages:

[14:23:49] INFO: Starting Scheduler
[Tue, 31 May 2022 14:23:49 +0200] Starting scheduler...
[14:23:49] INFO: Starting MQTT Listener
[cont-init.d] simplescheduler.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Tue, 31 May 2022 14:23:49 +0200] Starting MQTT Listner 
[14:23:49] INFO: Starting web server
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)

What's going wrong?

**Comment by arthurdent75** [comment] 2022-05-31 12:44
It seems you enabled the MQTT server, but with the wrong info

**Comment by maurizioandreotti60** [comment] 2022-05-31 12:46
Yes I enabled MQTT months and is working fine even with these errors. I can enable and disable schedules. So credentials are fine.

**Comment by maurizioandreotti60** [comment] 2022-05-31 12:50
Here the log from Mosquitto:

**Comment by arthurdent75** [comment] 2022-05-31 13:22
Thank you for the detailed report.
If everything is working, just ignore it.
I will leave the issue open while I investigate on that...

**Comment by arthurdent75** [comment] 2022-05-31 21:30
The error you are receiving is due to the PHP MQTT library (https://github.com/bluerhinos/phpMQTT), which I include "as is".
Since it is still the same since the last release, I cannot understand why it didn't throw the error before.
By the way, I can easily comment the library code that writes that error, because it seems to be a fake alarm.

**Comment by Kaibob2** [comment] 2022-06-06 17:48
Edit: All switch.simplescheduler_xxxxx_yyyyy entities are unavailable again.

```
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] simplescheduler.sh: executing... 
[19:37:39] INFO: Starting Scheduler
[Mon, 06 Jun 2022 19:37:39 +0200] Starting scheduler...
[19:37:39] INFO: Starting MQTT Listener
[cont-init.d] simplescheduler.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Mon, 06 Jun 2022 19:37:39 +0200] Starting MQTT Listner 
[19:37:39] INFO: Starting web server
PHP Notice:  Uninitialized string offset: 0 in /var/www/html/phpMQTT.php on line 244
PHP Notice:  Uninitialized string offset: 0 in /var/www/html/phpMQTT.php on line 250
PHP Notice:  Uninitialized string offset: 3 in /var/www/html/phpMQTT.php on line 251
Error:Connection failed! (Error: 0x00 0x00)
Notice: Uninitialized string offset: 0 in /var/www/html/phpMQTT.php on line 244
Notice: Uninitialized string offset: 0 in /var/www/html/phpMQTT.php on line 250
Notice: Uninitialized string offset: 3 in /var/www/html/phpMQTT.php on line 251
[Mon, 06 Jun 2022 19:37:39 +0200] Unable to connecto to MQTT broker!
```

**Comment by arthurdent75** [comment] 2022-06-06 18:33
Are you using Mosquitto as Home Assistant addon? Or it runs on a different server?

**Comment by Kaibob2** [comment] 2022-06-06 19:08
Mosquitto as Home Assistant addon.
This is (part of) the Mosquitto log:
```
1654542180: New client connected from 172.30.33.3:37294 as simplescheduler-629e4f6415c60 (p2, c1, k10, u'xxUSERxx').
1654542180: New connection from 172.30.33.3:37296 on port 1883.
1654542180: Client simplescheduler-629e4f6415c60 disconnected.
1654542180: New client connected from 172.30.33.3:37296 as simplescheduler-629e4f6416914 (p2, c1, k10, u'xxUSERxx').
```
There are hundreds of `Client simplescheduler-xxxxxxxxxxx disconnected` entries in the log!

And this is the simplescheduler log:
```
[fix-attrs.d] simplescheduler: applying... 
[fix-attrs.d] simplescheduler: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Simple Scheduler
 Simple timer on weekly base
-----------------------------------------------------------
 Add-on version: 0.60
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (amd64 / intel-nuc)
 Home Assistant Core: 2022.6.2
 Home Assistant Supervisor: 2022.05.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] simplescheduler.sh: executing... 
[20:24:45] INFO: Starting Scheduler
[Mon, 06 Jun 2022 20:24:45 +0200] Starting scheduler...
[20:24:45] INFO: Starting MQTT Listener
[cont-init.d] simplescheduler.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Mon, 06 Jun 2022 20:24:45 +0200] Starting MQTT Listner 
[20:24:45] INFO: Starting web server
[Mon, 06 Jun 2022 20:24:59 +0200] RCV: homeassistant/switch/simplescheduler/627257cd52b45/set --> OFF 
[Mon, 06 Jun 2022 20:24:59 +0200] PUB: homeassistant/switch/simplescheduler/627257cd52b45/state --> OFF 
[Mon, 06 Jun 2022 20:24:59 +0200] RCV: homeassistant/switch/simplescheduler/627288f36fea2/set --> OFF 
[Mon, 06 Jun 2022 20:24:59 +0200] PUB: homeassistant/switch/simplescheduler/627288f36fea2/state --> OFF 
[Mon, 06 Jun 2022 20:24:59 +0200] RCV: homeassistant/switch/simplescheduler/6272891530f23/set --> OFF 
[Mon, 06 Jun 2022 20:24:59 +0200] PUB: homeassistant/switch/simplescheduler/6272891530f23/state --> OFF 
[Mon, 06 Jun 2022 20:24:59 +0200] RCV: homeassistant/switch/simplescheduler/62728938b7450/set --> OFF 
[Mon, 06 Jun 2022 20:24:59 +0200] PUB: homeassistant/switch/simplescheduler/62728938b7450/state --> OFF 
Error:Connection failed! (Error: 0x00 0x00)
[Mon, 06 Jun 2022 20:25:01 +0200] RCV: homeassistant/switch/simplescheduler/627257cd52b45/set --> ON 
[Mon, 06 Jun 2022 20:25:01 +0200] PUB: homeassistant/switch/simplescheduler/627257cd52b45/state --> ON 
[Mon, 06 Jun 2022 20:25:01 +0200] RCV: homeassistant/switch/simplescheduler/627288f36fea2/set --> ON 
[Mon, 06 Jun 2022 20:25:01 +0200] PUB: homeassistant/switch/simplescheduler/627288f36fea2/state --> ON 
[Mon, 06 Jun 2022 20:25:01 +0200] RCV: homeassistant/switch/simplescheduler/6272891530f23/set --> ON 
[Mon, 06 Jun 2022 20:25:01 +0200] PUB: homeassistant/switch/simplescheduler/6272891530f23/state --> ON 
[Mon, 06 Jun 2022 20:25:01 +0200] RCV: homeassistant/switch/simplescheduler/62728938b7450/set --> ON 
[Mon, 06 Jun 2022 20:25:01 +0200] PUB: homeassistant/switch/simplescheduler/62728938b7450/state --> ON 
Error:Connection failed! (Error: 0x00 0x00)
[Mon, 06 Jun 2022 20:30:00 +0200] SCHED:  input_boolean/turn_off {"entity_id":"input_boolean.gemusebeet_an"} 
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
[Mon, 06 Jun 2022 20:44:00 +0200] SCHED:  input_boolean/turn_on {"entity_id":"input_boolean.jalousie_werkstatt_unlock"} 
[Mon, 06 Jun 2022 20:44:00 +0200] SCHED:  input_boolean/turn_on {"entity_id":"input_boolean.jalousie_wohnzimmer_unlock"} 
[Mon, 06 Jun 2022 20:44:00 +0200] SCHED:  input_boolean/turn_on {"entity_id":"input_boolean.jalousie_kueche_unlock"} 
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
Error:Connection failed! (Error: 0x00 0x00)
```

**Comment by maurizioandreotti60** [comment] 2022-07-28 08:53
> The error you are receiving is due to the PHP MQTT library (https://github.com/bluerhinos/phpMQTT), which I include "as is". Since it is still the same since the last release, I cannot understand why it didn't throw the error before. By the way, I can easily comment the library code that writes that error, because it seems to be a fake alarm.

Any news about a possible fix?

**Comment by maurizioandreotti60** [comment] 2022-07-28 08:55
> Edit: All switch.simplescheduler_xxxxx_yyyyy entities are unavailable again.
> 
> ```
> [cont-init.d] 00-banner.sh: exited 0.
> [cont-init.d] 01-log-level.sh: executing... 
> [cont-init.d] 01-log-level.sh: exited 0.
> [cont-init.d] simplescheduler.sh: executing... 
> [19:37:39] INFO: Starting Scheduler
> [Mon, 06 Jun 2022 19:37:39 +0200] Starting scheduler...
> [19:37:39] INFO: Starting MQTT Listener
> [cont-init.d] simplescheduler.sh: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> [Mon, 06 Jun 2022 19:37:39 +0200] Starting MQTT Listner 
> [19:37:39] INFO: Starting web server
> PHP Notice:  Uninitialized string offset: 0 in /var/www/html/phpMQTT.php on line 244
> PHP Notice:  Uninitialized string offset: 0 in /var/www/html/phpMQTT.php on line 250
> PHP Notice:  Uninitialized string offset: 3 in /var/www/html/phpMQTT.php on line 251
> Error:Connection failed! (Error: 0x00 0x00)
> Notice: Uninitialized string offset: 0 in /var/www/html/phpMQTT.php on line 244
> Notice: Uninitialized string offset: 0 in /var/www/html/phpMQTT.php on line 250
> Notice: Uninitialized string offset: 3 in /var/www/html/phpMQTT.php on line 251
> [Mon, 06 Jun 2022 19:37:39 +0200] Unable to connecto to MQTT broker!
> ```

I have the same issue. To fix I have to restart Simple Schedluer. Sometimes twice!

**Comment by arthurdent75** [comment] 2022-07-28 10:17
Ciao, sorry to hear that.
The last two releases took a lot of effort, and I had to work on other projects.
Just be patient another month... as soon as I will be back from holidays I will try to fix all the open issues.

**Comment by maurizioandreotti60** [comment] 2022-07-28 12:34
> Ciao, sorry to hear that. The last two releases took a lot of effort, and I had to work on other projects. Just be patient another month... as soon as I will be back from holidays I will try to fix all the open issues.

We can wait, it is not a "stop" issue ;-)

**Comment by arthurdent75** [comment] 2022-08-27 22:02
@maurizioandreotti60 @Kaibob2 are you still having this issue with the latest release?

**Comment by maurizioandreotti60** [comment] 2022-08-27 22:14
> @maurizioandreotti60 @Kaibob2 are you still having this issue with the latest release?

I will let you know when I'll be able to upgrade

**Comment by Kaibob2** [comment] 2022-08-28 08:45
> @Kaibob2 are you still having this issue with the latest release?

I haven't seen the error quite some time now, so I cannot say if this update fixed it. The error appeared randomly and I wasn't able to reproduce it once it was gone.
I installed 0.62 right now and everything is working fine. I'll report back if the error appears again.

**Comment by arthurdent75** [comment] 2022-08-28 09:07
> PHP Notice:  Uninitialized string offset: 0 in /var/www/html/phpMQTT.php on line 244
> PHP Notice:  Uninitialized string offset: 0 in /var/www/html/phpMQTT.php on line 250
> PHP Notice:  Uninitialized string offset: 3 in /var/www/html/phpMQTT.php on line 251

Disable the debug option in the addon configuration to hide these lines in the log.
This will not solve the connection error, but the log is easier to read

**Comment by arthurdent75** [comment] 2022-08-28 09:10
> I haven't seen the error quite some time now, so I cannot say if this update fixed it.

Actually, I changed something in the previous release (0.61) to try to solve this issue.
I forgot to mention it here... 😅

**Comment by maurizioandreotti60** [comment] 2022-08-28 09:16
> @maurizioandreotti60 @Kaibob2 are you still having this issue with the latest release?

As already reported by Kaibob2 I didn't see th eerror message in the last times, but now I see that 0.61 addressed the issue :-)
Anyway I'm still facing problems with MQTT. If I close the Add-on, the entities for the scheduling remains available; when I start again the Add-on, the MQTT entities will disappear. I need a further restart to have the MQTT entities working again.
On the Add-on log I don't see any error message.
This issue occurred on 0.61 as well.
Do I have to open a news issue for MQTT?

**Comment by arthurdent75** [comment] 2022-08-28 09:39
> Do I have to open a news issue for MQTT?

Yes, please

> If I close the Add-on, the entities for the scheduling remains available; when I start again the Add-on, the MQTT entities will disappear. I need a further restart to have the MQTT entities working again.

My idea is that MQTT switches remain in memory for a while so when you restart the addon it creates new entities (ending with _2) because they already exist. Then after a while the "original" entities timeout and disappear. With another restart, it will try to recreate and this time succeeded because the entity name is finally free.
You can easily check if this happens by looking in _Developer Tools --> States_ and filter for "simplescheduler"

**Comment by maurizioandreotti60** [comment] 2022-08-28 11:05
> > Do I have to open a news issue for MQTT?
> 
> Yes, please
> 
> > If I close the Add-on, the entities for the scheduling remains available; when I start again the Add-on, the MQTT entities will disappear. I need a further restart to have the MQTT entities working again.
> 
> My idea is that MQTT switches remain in memory for a while so when you restart the addon it creates new entities (ending with _2) because they already exist. Then after a while the "original" entities timeout and disappear. With another restart, it will try to recreate and this time succeeded because the entity name is finally free. You can easily check if this happens by looking in _Developer Tools --> States_ and filter for "simplescheduler"

This is partially true, let me explain.
I stopped the Add-on and the MQTT swithes were still available. After 10 minutes I can se the MQTT switches still alive.
I started the Add-on and the first original MQTT switch was still alive with e original name, while the other switches disapperead substitued by _2 swithches.
If I restart the Add-on, all the original switches disappeared substited by _2 ones.
Only a further restart will fix the issue.
So the problem occurs stopping the

**Comment by Kaibob2** [comment] 2022-08-28 14:30
> Actually, I changed something in the previous release (0.61) to try to solve this issue.
I forgot to mention it here... 😅
Great, that seemed to be the correct fix for the issue :)

> ...so when you restart the addon it creates new entities (ending with _2) 

This is a problem for me, too. I have a picture-eöements card as main page where the switch.simplescheduler_627257cd52b45_xxxxxx entities appear as icons. I the _2 issue comes up the card won't render as the entities aren't found.

**Comment by maurizioandreotti60** [comment] 2022-08-28 15:58
I Opened issue #80 for MQTT switches

**Comment by arthurdent75** [comment] 2022-08-31 20:32
I'm closing this one.
Will reopen if it happens again

**Closed by arthurdent75** 2022-08-31 20:32 UTC
